# Generated by Django 4.2.30 on 2026-07-12 16:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('grn_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('posting_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Goods Receipt',
                'verbose_name_plural': 'Goods Receipts',
                'db_table': 'purchasing_goods_receipts',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('po_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('posting_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('net_total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('tax_total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('grand_total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('billed', 'Billed'), ('cancelled', 'Cancelled')], default='draft', max_length=25)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('purchase_bill_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='accounting.vendor')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'purchasing_purchase_orders',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=19)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=19)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('received_qty', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('billed_qty', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='warehouse.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.purchaseorder')),
                ('target_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_items', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'purchasing_purchase_order_items',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=19)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=19)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('batch_no', models.CharField(blank=True, max_length=100)),
                ('serial_no', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_items', to='warehouse.item')),
                ('purchase_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_items', to='purchasing.purchaseorderitem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.goodsreceipt')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_items', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'purchasing_goods_receipt_items',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='accounting.vendor'),
        ),
    ]
