# Generated by Django 4.2.30 on 2026-07-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='product_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisitionitem',
            name='product_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='product_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='product_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
