# Generated by Django 4.2.30 on 2026-07-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_commissionstructure_deliverynote_deliverynoteitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='price_list',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='price_list',
        ),
        migrations.RemoveField(
            model_name='subscriptioncontract',
            name='price_list',
        ),
        migrations.AddField(
            model_name='quotation',
            name='price_list_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Soft link to product_catalogue.PriceList.', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='price_list_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Soft link to product_catalogue.PriceList.', null=True),
        ),
        migrations.AddField(
            model_name='subscriptioncontract',
            name='price_list_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Soft link to product_catalogue.PriceList.', null=True),
        ),
        migrations.DeleteModel(
            name='ItemPrice',
        ),
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
