# Generated by Django 4.2.30 on 2026-07-13 13:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetaryControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('entry_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('gasb_fund_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('entry_type', models.CharField(choices=[('pre_encumbrance', 'Pre-Encumbrance (Requisition)'), ('encumbrance', 'Encumbrance (Purchase Order)'), ('expenditure', 'Expenditure (Invoice/Payment)'), ('budget_amendment', 'Budget Amendment')], max_length=25)),
                ('status', models.CharField(choices=[('open', 'Open'), ('liquidated', 'Liquidated'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('description', models.TextField(blank=True)),
                ('entry_date', models.DateField()),
                ('source_document_type', models.CharField(blank=True, help_text='purchase_order, requisition, invoice', max_length=50)),
                ('source_document_id', models.UUIDField(blank=True, null=True)),
                ('liquidates_entry_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Budgetary Control Entry',
                'db_table': 'gov_budgetary_control',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='citizenservicerequest',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='citizenservicerequest',
            name='satisfaction_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5 citizen satisfaction rating', null=True),
        ),
        migrations.AddField(
            model_name='citizenservicerequest',
            name='target_resolution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizenservicerequest',
            name='ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='foiarequest',
            name='acknowledged_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foiarequest',
            name='denial_exemption',
            field=models.CharField(blank=True, help_text='e.g. FOIA Exemption (b)(6) — personal privacy', max_length=100),
        ),
        migrations.AddField(
            model_name='foiarequest',
            name='fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foiarequest',
            name='is_sensitive',
            field=models.BooleanField(default=False, help_text='Requires senior review before fulfillment'),
        ),
        migrations.AddField(
            model_name='foiarequest',
            name='requester_organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='foiarequest',
            name='requester_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='foiarequest',
            name='response_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gasbfund',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='permit',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='permit',
            name='conditions',
            field=models.TextField(blank=True, help_text='Conditions attached to the permit'),
        ),
        migrations.AddField(
            model_name='permit',
            name='fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permit',
            name='gasb_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits', to='government.gasbfund'),
        ),
        migrations.AddField(
            model_name='permit',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='review_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='reviewing_officer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tender',
            name='awarded_vendor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tender',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tender',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tender',
            name='eligibility_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='technical_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='disqualification_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='has_company_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='has_tax_clearance',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TenderEvaluationCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('criterion_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('weight_pct', models.DecimalField(decimal_places=2, help_text='Weight as percentage of total score', max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criteria', to='government.tender')),
            ],
            options={
                'db_table': 'gov_tender_evaluation_criteria',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PermitInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('inspection_type', models.CharField(max_length=100)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed / Requires Correction'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('inspector_name', models.CharField(blank=True, max_length=255)),
                ('inspector_employee_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('corrections_required', models.TextField(blank=True)),
                ('reinspection_required', models.BooleanField(default=False)),
                ('reinspection_date', models.DateField(blank=True, null=True)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='government.permit')),
            ],
            options={
                'db_table': 'gov_permit_inspections',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('grant_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('grant_type', models.CharField(choices=[('issued', 'Issued (Grantor)'), ('received', 'Received (Grantee)')], default='received', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active / Disbursing'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('counterpart_name', models.CharField(blank=True, help_text='Grantor (if received) or Grantee (if issued)', max_length=255)),
                ('counterpart_contact', models.EmailField(blank=True, max_length=254)),
                ('requested_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('approved_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('disbursed_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reporting_requirements', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('program_officer_id', models.UUIDField(blank=True, null=True)),
                ('program_officer_name', models.CharField(blank=True, max_length=255)),
                ('gasb_fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_applications', to='government.gasbfund')),
            ],
            options={
                'verbose_name': 'Grant Application',
                'db_table': 'gov_grant_applications',
                'abstract': False,
            },
        ),
    ]
