"""
Generates Django model Python source code from EntityDefinition objects.
The generated code is written to apps/{app}/models/generated.py by the
management command, then normal Django migrations handle the schema.
"""
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .definitions import EntityDefinition, FieldDefinition


# Maps entity field types → (Django field class, default kwargs)
_FIELD_MAP: dict[str, str] = {
    "string": "models.CharField(max_length={max_length}, blank={blank}, null={null})",
    "text": "models.TextField(blank={blank}, null={null})",
    "integer": "models.IntegerField(blank={blank}, null={null})",
    "float": "models.FloatField(blank={blank}, null={null})",
    "boolean": "models.BooleanField(default={default})",
    "date": "models.DateField(blank={blank}, null={null})",
    "datetime": "models.DateTimeField(blank={blank}, null={null})",
    "currency": "models.DecimalField(max_digits=19, decimal_places=4, blank={blank}, null={null})",
    "email": "models.EmailField(blank={blank}, null={null})",
    "phone": "models.CharField(max_length=32, blank={blank}, null={null})",
    "url": "models.URLField(blank={blank}, null={null})",
    "json": "models.JSONField(null=True, blank=True)",
    "select": "models.CharField(max_length=100, blank={blank}, null={null})",
    "multiselect": "models.JSONField(null=True, blank=True, default=list)",
    "geopoint": "models.JSONField(null=True, blank=True, help_text='{{lat, lng}}')",
    "geofence": "models.JSONField(null=True, blank=True, help_text='GeoJSON polygon')",
    "route": "models.JSONField(null=True, blank=True, help_text='GeoJSON linestring')",
}


def _field_to_source(field: "FieldDefinition") -> str:
    null = not field.required
    blank = not field.required
    default = repr(field.default) if field.default is not None else "False"
    max_length = field.max_length or 255

    if field.type == "link":
        target = field.target or "self"
        nullable = "" if field.required else ", null=True, blank=True"
        return (
            f'    {field.name} = models.ForeignKey("{target}", on_delete=models.PROTECT{nullable})'
        )
    if field.type == "table":
        target = field.target or "???"
        return f'    # {field.name} = related model "{target}" (reverse FK or M2M — define manually)'

    template = _FIELD_MAP.get(field.type)
    if not template:
        return f"    # {field.name}: unsupported field type '{field.type}'"

    django_field = template.format(null=null, blank=blank, default=default, max_length=max_length)
    return f"    {field.name} = {django_field}"


def generate_model_source(definition: "EntityDefinition") -> str:
    """Return Python source for a Django model class for the given EntityDefinition."""
    lines = [
        f"class {definition.entity}(BaseEntity):",
        f'    """Auto-generated from {definition.app}/entities/{definition.snake_name}.yaml"""',
    ]

    if definition.workflow:
        state_choices = ", ".join(f'("{s}", "{s}")' for s in definition.workflow.states)
        initial = definition.workflow.initial_state or definition.workflow.states[0]
        lines.append(f"    STATUS_CHOICES = [{state_choices}]")
        lines.append(
            f'    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default="{initial}")'
        )

    for field in definition.fields:
        lines.append(_field_to_source(field))

    if len(lines) == 2:  # only class + docstring
        lines.append("    pass")

    lines += [
        "",
        "    class Meta(BaseEntity.Meta):",
        f'        db_table = "{definition.app}_{definition.snake_name}"',
        f'        verbose_name = "{definition.display_label}"',
        f'        verbose_name_plural = "{definition.display_label_plural}"',
        "",
        "    def __str__(self):",
        '        return str(self.pk)',
        "",
    ]
    return "\n".join(lines)


def generate_app_models_file(app: str, definitions: list["EntityDefinition"]) -> str:
    """Generate the full models/generated.py content for an app."""
    header = (
        "# AUTO-GENERATED by ochre metadata engine. DO NOT EDIT MANUALLY.\n"
        "# Re-run `python manage.py generate_entity_models` to update.\n"
        "from django.db import models\n"
        "from core.metadata_engine.base_entity import BaseEntity\n\n"
    )
    body = "\n\n".join(generate_model_source(d) for d in definitions)
    return header + body + "\n"
