# Generated by Django 4.2.30 on 2026-07-12 17:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('plan_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('service_type', models.CharField(choices=[('voice', 'Voice'), ('data', 'Data'), ('sms', 'SMS'), ('bundle', 'Bundle'), ('iot', 'IoT')], default='bundle', max_length=20)),
                ('billing_type', models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid'), ('hybrid', 'Hybrid')], default='postpaid', max_length=20)),
                ('monthly_fee', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('included_minutes', models.IntegerField(default=0)),
                ('included_sms', models.IntegerField(default=0)),
                ('included_data_mb', models.IntegerField(default=0)),
                ('overage_rate_per_unit', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('contract_months', models.PositiveSmallIntegerField(default=0, help_text='0 = month-to-month')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'telecom_service_plans',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('msisdn', models.CharField(blank=True, db_index=True, help_text='Mobile Subscriber Integrated Services Digital Network Number', max_length=20)),
                ('iccid', models.CharField(blank=True, db_index=True, help_text='SIM card ICCID', max_length=22)),
                ('status', models.CharField(choices=[('pending', 'Pending Activation'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('prepaid_balance', models.DecimalField(decimal_places=4, default=0, help_text='For prepaid: remaining balance', max_digits=19)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='telecom.serviceplan')),
            ],
            options={
                'db_table': 'telecom_subscriptions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('subscriber_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('crm_account_id', models.UUIDField(blank=True, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'telecom_subscribers',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('usage_type', models.CharField(choices=[('voice_call', 'Voice Call'), ('sms', 'SMS'), ('data', 'Data Session'), ('mms', 'MMS')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('duration_seconds', models.IntegerField(default=0)),
                ('data_volume_mb', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('destination', models.CharField(blank=True, help_text='For voice/SMS: destination number', max_length=50)),
                ('is_roaming', models.BooleanField(default=False)),
                ('is_rated', models.BooleanField(default=False)),
                ('rated_amount', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='telecom.servicesubscription')),
            ],
            options={
                'db_table': 'telecom_usage_records',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelecomInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('recurring_charges', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('usage_charges', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('taxes', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('grand_total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('accounting_invoice_id', models.UUIDField(blank=True, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='telecom.subscriber')),
            ],
            options={
                'db_table': 'telecom_invoices',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='servicesubscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='telecom.subscriber'),
        ),
    ]
