# Generated by Django 4.2.30 on 2026-07-12 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('under_maintenance', 'Under Maintenance'), ('scrapped', 'Scrapped'), ('sold', 'Sold')], default='draft', max_length=25)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('current_value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('salvage_value', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('useful_life_years', models.PositiveSmallIntegerField()),
                ('depreciation_method', models.CharField(blank=True, max_length=30)),
                ('depreciation_start_date', models.DateField(blank=True, null=True)),
                ('fully_depreciated', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100)),
                ('serial_no', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('custodian_employee_id', models.UUIDField(blank=True, null=True)),
                ('purchase_order_id', models.UUIDField(blank=True, null=True)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('disposal_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'assets',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance'), ('units_of_production', 'Units of Production')], default='straight_line', max_length=30)),
                ('useful_life_years', models.PositiveSmallIntegerField(default=5)),
                ('salvage_value_pct', models.DecimalField(decimal_places=2, default=0, help_text='Residual value as % of purchase price', max_digits=5)),
                ('asset_account_id', models.UUIDField(blank=True, null=True)),
                ('depreciation_expense_account_id', models.UUIDField(blank=True, null=True)),
                ('accumulated_depreciation_account_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'db_table': 'asset_categories',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('movement_date', models.DateField()),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('from_custodian_id', models.UUIDField(blank=True, null=True)),
                ('to_custodian_id', models.UUIDField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_movements_approved', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='asset_management.asset')),
            ],
            options={
                'db_table': 'asset_movements',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('inspection', 'Inspection')], default='preventive', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('description', models.TextField(blank=True)),
                ('performed_by', models.CharField(blank=True, max_length=255)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='asset_management.asset')),
            ],
            options={
                'db_table': 'asset_maintenance',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('schedule_date', models.DateField()),
                ('depreciation_amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=4, max_digits=19)),
                ('book_value_after', models.DecimalField(decimal_places=4, max_digits=19)),
                ('is_posted', models.BooleanField(default=False)),
                ('journal_entry_id', models.UUIDField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_schedule', to='asset_management.asset')),
            ],
            options={
                'db_table': 'asset_depreciation_schedule',
                'ordering': ['asset', 'schedule_date'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='asset_management.assetcategory'),
        ),
    ]
