# Generated by Django 4.2.30 on 2026-07-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre_audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='ochre_audit_entity_7da4d5_idx',
            old_name='ochre_audit_entity_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='ochre_audit_user_id_74ae89_idx',
            old_name='ochre_audit_user_ts_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, help_text='create / update / delete / submit / cancel', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='after',
            field=models.JSONField(blank=True, help_text='Snapshot after change', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='before',
            field=models.JSONField(blank=True, help_text='Snapshot before change', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='diff',
            field=models.JSONField(blank=True, help_text='Field-level diff {field: [old, new]}', null=True),
        ),
    ]
