# Generated by Django 4.2.30 on 2026-07-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odum_audit', '0002_rename_ochre_audit_entity_idx_ochre_audit_entity_7da4d5_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='odum_audit__entity_ae7582_idx',
            old_name='odum_audit_entity_7da4d5_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='odum_audit__user_id_fa02e9_idx',
            old_name='odum_audit_user_id_74ae89_idx',
        ),
    ]
