# Generated by Django 4.2.30 on 2026-07-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odum_ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agenthandoffrequest',
            new_name='odum_agent__company_e9bbcf_idx',
            old_name='odum_handoffs_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='agenthandoffrequest',
            new_name='odum_agent__run_id_7eb43e_idx',
            old_name='odum_handoffs_run_status_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrun',
            new_name='odum_agent__agent_i_a21f64_idx',
            old_name='odum_agent_runs_agent_status_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrun',
            new_name='odum_agent__company_bb2623_idx',
            old_name='odum_agent_runs_company_status_idx',
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='service_account_id',
            field=models.UUIDField(blank=True, help_text="OdumUser UUID acting as the agent's RBAC identity for all writes", null=True),
        ),
        migrations.AlterField(
            model_name='agenthandoffrequest',
            name='edited_payload',
            field=models.JSONField(blank=True, help_text="Human's edited version of proposed_action", null=True),
        ),
    ]
