# Generated by Django 4.2.30 on 2026-07-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_bin_remove_stockentrydetail_batch_no_item_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID of the product_catalogue.Product this Item extends.', null=True),
        ),
    ]
