# Generated by Django 4.2.30 on 2026-07-12 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('odum_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='odumuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='abbr',
            field=models.CharField(help_text='Short abbreviation used in document numbering', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2),
        ),
        migrations.AlterField(
            model_name='entitypermission',
            name='entity',
            field=models.CharField(help_text="Entity name, e.g. 'SalesInvoice'", max_length=100),
        ),
        migrations.AlterField(
            model_name='entitypermission',
            name='row_filter',
            field=models.JSONField(blank=True, help_text='Optional JSON filter applied to restrict which rows are visible', null=True),
        ),
        migrations.AlterField(
            model_name='odumuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='odumuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='odumuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='role',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Null = platform-wide role', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='odum_auth.company'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System roles cannot be deleted'),
        ),
    ]
