# Generated by Django 4.2.30 on 2026-07-14 07:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('provider', models.CharField(db_index=True, help_text='Driver name: mtn_momo, airteltigo, vodafone_cash, cash, bank_transfer', max_length=50)),
                ('provider_tx_id', models.CharField(blank=True, db_index=True, help_text="Provider's own transaction ID (used for idempotency on webhooks).", max_length=255, null=True)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Computed key used to prevent duplicate processing.', max_length=255)),
                ('payable_document_id', models.CharField(db_index=True, max_length=36)),
                ('payable_document_type', models.CharField(db_index=True, help_text='Model name: GovernmentRevenueBill, SalesInvoice, LoanAccount…', max_length=100)),
                ('revenue_type', models.CharField(db_index=True, help_text='Classification: property_rate, permit_fee, market_toll, service_charge, sales, loan_repayment…', max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('payer_reference', models.CharField(blank=True, help_text='Phone number, account number, or collector ID.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (collection)'), ('outbound', 'Outbound (disbursement)')], default='inbound', max_length=10)),
                ('journal_entry_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('raw_request', models.JSONField(default=dict)),
                ('raw_response', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'payments_events',
                'abstract': False,
                'indexes': [models.Index(fields=['provider', 'provider_tx_id'], name='pay_evt_provider_tx_idx'), models.Index(fields=['payable_document_type', 'payable_document_id'], name='pay_evt_doc_idx'), models.Index(fields=['revenue_type', 'status'], name='pay_evt_rev_type_idx')],
            },
        ),
    ]
