# Generated by Django 4.2.30 on 2026-07-12 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. INV, PO, SO, GRN, PAY', max_length=50)),
                ('prefix', models.CharField(blank=True, help_text='e.g. INV-2026-', max_length=20)),
                ('current_number', models.PositiveIntegerField(default=0)),
                ('padding', models.PositiveSmallIntegerField(default=5, help_text='Zero-pad width')),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Number Series',
                'verbose_name_plural': 'Number Series',
                'db_table': 'odum_number_series',
                'unique_together': {('name', 'company_id')},
            },
        ),
    ]
