# Generated by Django 4.2.30 on 2026-07-12 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='website.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'db_table': 'website_blog_categories',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('target_entity', models.CharField(blank=True, help_text='e.g. crm.Lead — entity to create on submit', max_length=100)),
                ('success_message', models.TextField(blank=True, default='Thank you for your submission.')),
                ('redirect_url', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('send_confirmation_email', models.BooleanField(default=False)),
                ('email_field', models.CharField(blank=True, help_text="Field name whose value is the submitter's email", max_length=50)),
            ],
            options={
                'db_table': 'website_web_forms',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.JSONField(default=dict, help_text='Block-based content (compatible with a page-builder renderer)')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.CharField(blank=True, default='default', max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='website.webpage')),
            ],
            options={
                'db_table': 'website_pages',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebFormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('data', models.JSONField(help_text='Submitted field values as {field_name: value}')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_entity_id', models.UUIDField(blank=True, help_text='ID of the entity created from this submission', null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='website.webform')),
            ],
            options={
                'db_table': 'website_form_submissions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebFormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('field_name', models.CharField(help_text='Maps to entity field name', max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('phone', 'Phone'), ('textarea', 'Text Area'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('number', 'Number'), ('date', 'Date')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, help_text='For select fields: list of options', null=True)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='website.webform')),
            ],
            options={
                'db_table': 'website_web_form_fields',
                'ordering': ['form', 'sequence'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('featured_image', models.CharField(blank=True, max_length=500)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='website.blogcategory')),
            ],
            options={
                'db_table': 'website_blog_posts',
                'ordering': ['-published_at'],
                'abstract': False,
            },
        ),
    ]
