# Generated by Django 4.2.30 on 2026-07-13 12:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_holidaylist_shift_employee_address_and_more'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('loan_number', models.CharField(blank=True, db_index=True, max_length=30)),
                ('loan_type', models.CharField(choices=[('advance', 'Salary Advance'), ('loan', 'Formal Loan')], default='loan', max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual interest rate % (0 for interest-free advances)', max_digits=5)),
                ('repayment_periods', models.PositiveSmallIntegerField(help_text='Number of payroll periods over which to recover the loan')),
                ('monthly_installment', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('total_repayable', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('outstanding_balance', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('active', 'Active (recovering)'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approved_by_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='hrm.employee')),
                ('repayment_start_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_starts', to='payroll.payrollperiod')),
            ],
            options={
                'db_table': 'payroll_employee_loans',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatutoryPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('country_code', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 or alpha-3', max_length=3)),
                ('country_name', models.CharField(max_length=100)),
                ('name', models.CharField(help_text='e.g. Ghana PAYE + SSNIT 2025', max_length=150)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'payroll_statutory_packs',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='run_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('bonus', 'Bonus / Off-Cycle'), ('correction', 'Correction')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='total_loan_deductions',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='loan_deduction_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='shift_differential_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='working_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.CreateModel(
            name='StatutoryRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('abbr', models.CharField(blank=True, max_length=20)),
                ('rule_type', models.CharField(choices=[('employee', 'Employee Contribution'), ('employer', 'Employer Contribution'), ('income_tax', 'Income Tax (PAYE)')], max_length=30)),
                ('calc_method', models.CharField(choices=[('fixed_rate', 'Fixed Rate % of gross'), ('bracket', 'Bracket / Progressive'), ('flat_amount', 'Flat Amount'), ('fixed_rate_of_base', 'Fixed Rate % of base salary')], max_length=30)),
                ('rate', models.DecimalField(decimal_places=4, default=0, help_text='Percentage rate (e.g. 5.5 for 5.5%) — used when calc_method is fixed_rate', max_digits=7)),
                ('brackets', models.JSONField(blank=True, default=list)),
                ('cap_amount', models.DecimalField(decimal_places=4, default=0, help_text='Max deduction per period (0 = no cap)', max_digits=19)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('applies_to_component', models.ForeignKey(blank=True, help_text="If set, rule operates on this component's amount rather than gross", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statutory_rules', to='payroll.salarycomponent')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='payroll.statutorypack')),
            ],
            options={
                'db_table': 'payroll_statutory_rules',
                'ordering': ['pack', 'sequence'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanRepaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Admin-added custom fields (backed by JSONB).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('installment_no', models.PositiveSmallIntegerField()),
                ('principal_component', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('interest_component', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deducted', 'Deducted'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('salary_slip_id', models.UUIDField(blank=True, null=True)),
                ('deducted_on', models.DateField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='payroll.employeeloan')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_installments', to='payroll.payrollperiod')),
            ],
            options={
                'db_table': 'payroll_loan_repayment_schedule',
                'ordering': ['loan', 'installment_no'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='statutory_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_entries', to='payroll.statutorypack'),
        ),
    ]
